Python Assignment: Data Structures, Functions, Numpy & Pandas

Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse

In [ ]:
lst = [10, 20, 30, 40, 50]
print("Original list:", lst)

# append
lst.append(60)
print("After append(60):", lst)

# extend
lst2 = [70, 80]
lst.extend(lst2)
print("After extend([70, 80]):", lst)

# insert
lst.insert(2, 25)
print("After insert(2, 25):", lst)

# remove
lst.remove(30)
print("After remove(30):", lst)

# pop
popped_element = lst.pop(0)
print("Popped element from index 0:", popped_element)
print("After pop(0):", lst)

# index
index_of_40 = lst.index(40)
print("Index of 40:", index_of_40)

# count
count_of_25 = lst.count(25)
print("Count of 25:", count_of_25)

# sort
lst.sort()
print("After sort():", lst)

# reverse
lst.reverse()
print("After reverse():", lst)

# clear
lst.clear()
print("After clear():", lst)

Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(30): [10, 20, 25, 40, 50, 60, 70, 80]
Popped element from index 0: 10
After pop(0): [20, 25, 40, 50, 60, 70, 80]
Index of 40: 2
Count of 25: 1
After sort(): [20, 25, 40, 50, 60, 70, 80]
After reverse(): [80, 70, 60, 50, 40, 25, 20]
After clear(): []


2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [ ]:
student_names = {"Narendra","Virat","Rohit"}
print("Original Tuple:",student_names)

student_names[1]="Dhoni"
print("Modified Tuple:",student_names)


Original Tuple: {'Virat', 'Narendra', 'Rohit'}


TypeError: 'set' object does not support item assignment

In [ ]:
print("It Gives Error Because Tuples are Immutable means once the tuple is created we cannot update, delete or add elements to the tuple")

It Gives Error Because Tuples are Immutable means once the tuple is created we cannot update, delete or add elements to the tuple


3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [ ]:
set_of_integers = {1,2,3,4,4,5,6,6,7}
print(set_of_integers)

print("Set does not allow duplicate values it only allows unique values, therefore duplicate values are removed and output we get is {1,2,3,4,5,6,7}")

{1, 2, 3, 4, 5, 6, 7}
Set does not allow duplicate values it only allows unique values, therefore duplicate values are removed and output we get is {1,2,3,4,5,6,7}


4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [ ]:
dict = {'name':'Narendra','age':20,'city':'Pune'}
print("Original Dictionary",dict)

dict['age']=23
dict['email']='narendrachavan451@gmail.com'
print("Final Dictionary After Update Age to 23 and adding new key email:",dict)

Original Dictionary {'name': 'Narendra', 'age': 20, 'city': 'Pune'}
Final Dictionary After Update Age to 23 and adding new key email: {'name': 'Narendra', 'age': 23, 'city': 'Pune', 'email': 'narendrachavan451@gmail.com'}


5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [ ]:
age = int(input("Enter your age: "))

if age <= 0:
    print("Please enter a Valid Age numver")
elif age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote")

Enter your age: 27
You are eligible to vote.


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [ ]:
marks = int(input("Enter your marks: "))
if marks < 0:
    print("Please enter a valid marks number")
elif marks >=90:
    print("Your Grade is A")
elif marks >=75 and marks <=89:
    print("Your Grade is B")
elif marks >=50 and marks <=74:
    print("Your Grade is C")
else:
    print("Your Grade is Fail")

Enter your marks: 49
Your Grade is Fail


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
num = -111
if num > 0:
     if num % 2 ==0:
        print("The Number is Positive and Even")
     else:
        print("The Number is Positive and Odd")

else:
    if num == 0:
        print("The Number is Zero")
    else:
        print("The Number is Negative")

The Number is Negative


Section B: Numpy
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [ ]:
import numpy as np
scalar = np.array(5)
print("Scalar using np.array(5):",scalar)

one_D_array = np.array([1,2,3,4,5])
print("One Dimensional Array:",one_D_array)
Two_D_array = np.array([[10,20,30],[40,50,60]])
print("Two Dimensional Array:",Two_D_array)


Scalar using np.array(5): 5
One Dimensional Array: [1 2 3 4 5]
Two Dimensional Array: [[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [ ]:
import random
import numpy as np
array = np.random.randint(0,100,(4,4))
print("Random 4x4 Dimensional Array:",array)

Random 4x4 Dimensional Array: [[78 59 50 81]
 [22 20 79 77]
 [24 29 67 44]
 [ 7 26 54 12]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
import numpy as np
import pandas as pd

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(array,columns=['A','B','C'])
print("Array with Column Names\n", df)

Array with Column Names
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


Section C: Exploring Pandas
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [ ]:
import pandas as pd
import numpy as np

Data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Alice', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan'],
    'Age': [24, 27, 22, 32, 24, 29, 35, 26, 30, 23],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'New York', 'Miami', 'Dallas', 'Seattle', 'Boston', 'Austin'],
    'Salary': [50000, 60000, 45000, np.nan, 50000, 70000, 80000, 55000, np.nan, 48000]
}
df = pd.DataFrame(Data)

print("Original DataFrame:")
display(df)

Original DataFrame:


Name  Age         City   Salary
0    Alice   24     New York  50000.0
1      Bob   27  Los Angeles  60000.0
2  Charlie   22      Chicago  45000.0
3    David   32      Houston      NaN
4    Alice   24     New York  50000.0
5      Eve   29        Miami  70000.0
6    Frank   35       Dallas  80000.0
7    Grace   26      Seattle  55000.0
8    Heidi   30       Boston      NaN
9     Ivan   23       Austin  48000.0

In [ ]:
selected_colums = df[['Name','City']]
print("Selected Columns\n",selected_colums)

Selected Columns
       Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4    Alice     New York
5      Eve        Miami
6    Frank       Dallas
7    Grace      Seattle
8    Heidi       Boston
9     Ivan       Austin


In [ ]:
df.drop(['City'],axis=1,inplace=True)
print("DataFrame After Dropping City Column\n",df)


DataFrame After Dropping City Column
       Name  Age   Salary
0    Alice   24  50000.0
1      Bob   27  60000.0
2  Charlie   22  45000.0
3    David   32      NaN
4    Alice   24  50000.0
5      Eve   29  70000.0
6    Frank   35  80000.0
7    Grace   26  55000.0
8    Heidi   30      NaN
9     Ivan   23  48000.0


In [ ]:
df.isnull()

Name    Age  Salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False    True
4  False  False   False
5  False  False   False
6  False  False   False
7  False  False   False
8  False  False    True
9  False  False   False

In [ ]:
df.fillna(df['Salary'].mean(),inplace=True)
print("DataFrame After Filling Missing Values in Salary Column\n",df)

DataFrame After Filling Missing Values in Salary Column
       Name  Age   Salary
0    Alice   24  50000.0
1      Bob   27  60000.0
2  Charlie   22  45000.0
3    David   32  57250.0
4    Alice   24  50000.0
5      Eve   29  70000.0
6    Frank   35  80000.0
7    Grace   26  55000.0
8    Heidi   30  57250.0
9     Ivan   23  48000.0


In [ ]:
remove_duplicate_rows = df.drop_duplicates()
print("DataFrame After Removing Duplicate Rows\n",remove_duplicate_rows)

DataFrame After Removing Duplicate Rows
       Name  Age   Salary
0    Alice   24  50000.0
1      Bob   27  60000.0
2  Charlie   22  45000.0
3    David   32  57250.0
5      Eve   29  70000.0
6    Frank   35  80000.0
7    Grace   26  55000.0
8    Heidi   30  57250.0
9     Ivan   23  48000.0
